  CREATE UNIQUE INDEX "ITEM_PK" ON "ITEM" ("ITEM") 
  ;

  CREATE UNIQUE INDEX "LOC_PK" ON "LOC" ("LOC") 
  ;

  CREATE UNIQUE INDEX "SITEM_LOC_SOH_PK" ON "ITEM_LOC_SOH" ("LOC", "ITEM", "DEPT") 
  ; 