  CREATE TABLE "ITEM_LOC_SOH" 
   (	"ITEM" VARCHAR2(25) NOT NULL ENABLE, 
	"LOC" NUMBER(10,0) NOT NULL ENABLE, 
	"DEPT" NUMBER(4,0) NOT NULL ENABLE, 
	"UNIT_COST" NUMBER(20,4) NOT NULL ENABLE, 
	"STOCK_ON_HAND" NUMBER(12,4) NOT NULL ENABLE, 
	 CONSTRAINT "SITEM_LOC_SOH_PK" PRIMARY KEY ("LOC", "ITEM", "DEPT")
  USING INDEX  ENABLE
   ) 
  PARTITION BY LIST ("LOC") AUTOMATIC 
 (PARTITION "P1"  VALUES (1) , 
 PARTITION "SYS_P2159139"  VALUES (101) , 
 PARTITION "SYS_P2159140"  VALUES (102) , 
 PARTITION "SYS_P2159141"  VALUES (103) ) ;

  CREATE TABLE "ITEM" 
   (	"ITEM_KEY" NUMBER(10,0) NOT NULL ENABLE, 
	"ITEM" VARCHAR2(25) NOT NULL ENABLE, 
	"DEPT" NUMBER(4,0) NOT NULL ENABLE, 
	"ITEM_DESC" VARCHAR2(25) NOT NULL ENABLE, 
	 CONSTRAINT "ITEM_PK" PRIMARY KEY ("ITEM")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "LOC" 
   (	"LOC" NUMBER(10,0) NOT NULL ENABLE, 
	"LOC_DESC" VARCHAR2(25) NOT NULL ENABLE, 
	 CONSTRAINT "LOC_PK" PRIMARY KEY ("LOC")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "USER_ACESS" 
   (	"USER_ID" VARCHAR2(25) NOT NULL ENABLE, 
	"USER_DESC" VARCHAR2(50) NOT NULL ENABLE, 
	"DEPT" NUMBER(4,0) NOT NULL ENABLE, 
	"CREATE_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, 
	"CREATE_USER" VARCHAR2(25) NOT NULL ENABLE
   ) ;

  ALTER TABLE "ITEM_LOC_SOH" ADD CONSTRAINT "FK_ITEM_LOC_SOH_ITEM" FOREIGN KEY ("ITEM")
	  REFERENCES "ITEM" ("ITEM") ENABLE;
  ALTER TABLE "ITEM_LOC_SOH" ADD CONSTRAINT "FK_ITEM_LOC_SOH_LOC" FOREIGN KEY ("LOC")
	  REFERENCES "LOC" ("LOC") ENABLE; 